### ISSUE TITLE
Support for multiple Go projects in a monorepo

### ISSUE THREAD

**Issue by radhus** [bazelbuild/bazel-gazelle#634]
### What version of gazelle are you using?

0.18.1

### What version of rules_go are you using?

0.19.0

### What version of Bazel are you using?

0.28.1

### Does this issue reproduce with the latest releases of all the above?

I think so.

### What operating system and processor architecture are you using?

macOS / x64

### What did you do?

I want to have a monorepo using Bazel with multiple Go projects inside, all imported their **different** dependencies to `WORKSPACE` from their respective `go.mod` files, without conflicting versions of their dependencies.

#### What I've tried:

1. Use an existing monorepo using bazel, without any Go code.
1. Create two new Go projects inside, e.g. `src/proj1` and `src/proj2`
1. Initialize both Go projects with `go.mod` and different dependencies.
1. Use gazelle to import `go.mod` dependencies to `WORKSPACES`

For the last step, I've tried:

1. `bazel run //:gazelle -- update-repos -from_file=src/proj1/go.mod -from_file=src/proj2/go.mod`
2. `bazel run //:gazelle -- update-repos -from_file=src/proj1/go.mod && bazel run //:gazelle -- update-repos from_file=src/proj2/go.mod`
3. `bazel run //:gazelle -- update-repos -from_file=src/proj1/go.mod -to_macro=go_deps.bzl%go_deps_proj1 &&  bazel run //:gazelle -- update-repos -from_file=src/proj2/go.mod -to_macro=go_deps.bzl%go_deps_proj2`

### What did you expect to see?

No build failures or dependency conflicts when building both `proj1` and `proj2`.

### What did you see instead?

Results related to the command list above:

1. Only dependencies from `proj2` are imported to `WORKSPACE`.
2. All dependencies are imported (as `-prune` is not used), but versions from `proj2` overwrite versions from `proj1`.
3. Versions from the macro imported last in `WORKSPACE` wins.

### Questions

Is this something that is already supported, but I'm just missing something?

If not, is this something that you want to support in Gazelle, and what is needed to implement it?

**Comment by jayconrod** [comment]
At the moment, `gazelle update-repos -from_file=go.mod` only supports one go.mod file. It essentially runs `go list -m -json all`, then translates the output to `go_repository` rules, which are merged into WORKSPACE.

How would you expect that to handle multiple go.mod files? Specifically how should it resolve differences in versions of dependencies? It can only pick one version of each, so I guess you would want the maximum version of each (same as what Go's MVS would give you).

As a workaround, you could create a synthetic go.mod file containing all requirements, then use `gazelle update-repos -from_file=go.mod` on that.

**Comment by radhus** [comment]
Thanks for answering @jayconrod !

> How would you expect that to handle multiple go.mod files? Specifically how should it resolve differences in versions of dependencies? It can only pick one version of each, so I guess you would want the maximum version of each (same as what Go's MVS would give you).

In an ideal case, I'd like to be able to build multiple sub-projects that has different versions of dependencies. So preferably not reduced to one single version per dependency package.

I don't know how to solve that resolution in a good way, but perhaps if the dependency rules could be prefixed or suffixed in some way that it includes either some version or a given argument (where e.g. I could then enter the sub-project's name).

> As a workaround, you could create a synthetic go.mod file containing all requirements, then use `gazelle update-repos -from_file=go.mod` on that.

That would reduce the dependencies to only a single version for each dependency though, forcing all sub-projects to have the same version of dependencies (hence upgrading a dependency means making the new version of the dependency work in all sub-projects).

Do you think this kind of use-case is out of scope for gazelle?

**Comment by jayconrod** [comment]
> In an ideal case, I'd like to be able to build multiple sub-projects that has different versions of dependencies. So preferably not reduced to one single version per dependency package.

I think the best way to accomplish that would be to create a separate WORKSPACE for each module. You can reference other workspaces within the repository using the `local_repository` rule (analogous to `replace` directives in go.mod).

If you're using a single WORKSPACE for the whole repo, you're likely to run into conflicts. For example, say you have module A that depends on X v1.1.0, and module B that depends on X v1.2.0. You have two `go_repository` rules for the different versions of X. If you build a binary that depends on packages in A and B, that binary will get two copies of X at different versions, which will cause problems.

> Do you think this kind of use-case is out of scope for gazelle?

It does seem out of scope to me. Gazelle is meant to map `go build`'s conventions to Bazel build files. go.mod files are analogous to WORKSPACE files, so I don't think it makes sense for Gazelle to map multiple go.mod files to a single WORKSPACE file.

The most similar thing I can think of is the way vendoring works in GOPATH mode. Each module could have a vendor directory (perhaps built with `go mod vendor`). I think Gazelle would work with that more or less automatically. However, you're still at risk of conflicts as described above.

**Comment by krlvi** [comment]
Has the Gazelle team considered prefixing `go_repository` name attributes with the name of the project?

**Comment by jayconrod** [comment]
> Has the Gazelle team considered prefixing go_repository name attributes with the name of the project?

That seems like a specialized use case, out of scope for Gazelle. It also doesn't resolve the issue with conflicts between multiple versions of dependencies.

**Comment by chrismatix** [comment]
For anybody else coming across this issue: We have implemented a simple tool that merges all the modules in your project into a single `go.mod` https://github.com/airyhq/airy/tree/develop/tools/update-deps

It also takes care of updating package versions if there is a later version in another module.

**Comment by faximan** [comment]
> I think the best way to accomplish that would be to create a separate WORKSPACE for each module. You can reference other workspaces within the repository using the `local_repository` rule.

How does this solve the diamond dependency problem?

If WORKSPACE A references WORKSPACE B (through `local_repository`), and A and B have different versions of dependency Foo, and there is a build target that depends on both A's Foo and B's Foo, you still have the problem, no?

**Comment by dwj300** [comment]
> > I think the best way to accomplish that would be to create a separate WORKSPACE for each module. You can reference other workspaces within the repository using the `local_repository` rule.
> 
> How does this solve the diamond dependency problem?
> 
> If WORKSPACE A references WORKSPACE B (through `local_repository`), and A and B have different versions of dependency Foo, and there is a build target that depends on both A's Foo and B's Foo, you still have the problem, no?

@faximan Yeah I'm struggling with the same issue...
